PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX : <http://test/michel#>

INSERT DATA { 
    :hand :partOf :arm .
    :arm :partOf :body .
    :partOf a owl:ObjectProperty;
            a owl:TransitiveProperty .
}
