PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX : <http://test/michel#>
SELECT ?graph ?subject ?object ?result
FROM NAMED <http://www.ontotext.com/implicit>
FROM NAMED <http://www.ontotext.com/explicit>
#FROM NAMED :graph1
WHERE { 
    GRAPH ?graph { ?subject :partOf ?object. }
#    BIND (IF(?graph = :graph1, "c'est graph1", "c'est pas graph1") AS ?result)
    BIND ( IF ( ?graph = <http://www.ontotext.com/implicit>, "inferred", "not inferred") AS ?result)
}