PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX mm: <http://www.flandersmake.be/ontology/mm#> 
PREFIX proc: <http://www.flandersmake.be/ontology/proc#> 

SELECT ?en ?pn ?nn
WHERE {
    proc:EP11 mm:allElements ?e.
    ?e mm:definition ?ed.
    ?ed proc:name ?en.
    ?p mm:elements ?e.
    ?p mm:definition ?pd.
    ?pd proc:name ?pn.
    OPTIONAL {
        ?e proc:nextStepExec ?n.
        ?n mm:definition ?nd.
	    ?nd proc:name ?nn.
    }
}

