PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX mm: <http://www.flandersmake.be/ontology/mm#> 
PREFIX proc: <http://www.flandersmake.be/ontology/proc#> 
PREFIX : <http://www.flandersmake.be/ontology/mich#> 

INSERT DATA {
    :Gluing2
        rdf:type proc:ProcessExec;
        proc:name "Gluing sample 2 20240128";
        mm:definition :Gluing.
}