PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX onto: <http://www.ontotext.com/>
prefix mm: <http://www.flandersmake.be/ontology/mm#> 
prefix accnc: <http://fm.be/dtdesign/acncn#>

SELECT ?prop ?class ?isblank ?classi ?other2
where {
    ?prop rdf:type rdf:Property.
    # ?class rdf:type owl:Class.
    ?prop rdfs:domain ?class.
    bind ( isblank(?class) as ?isblank )
    MINUS {
        ?prop rdfs:domain ?other.
        ?other rdfs:subClassOf ?class.
        MINUS {
            ?class rdfs:subClassOf ?other.
        } 
    } 
    ?classi rdfs:subClassOf ?class.
    filter ( ?classi != ?class)
    filter not exists 
    {
        ?other2 rdfs:subClassOf ?class.
        ?classi rdfs:subClassOf ?other2.
        filter ( ?other2 != ?classi)
        filter ( ?other2 != ?class)
    }
    FILTER( !STRSTARTS(STR(?prop) , 'http://www.w3.org'))
    # VALUES ?class2 { owl:Nothing accnc:CNCExec accnc:CMMExec }
    # values ?classi { owl:Nothing }
 }