PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX onto: <http://www.ontotext.com/>
prefix mm: <http://www.flandersmake.be/ontology/mm#> 
prefix accnc: <http://fm.be/dtdesign/acncn#>

SELECT ?prop ?class1 ?class2
where {
    ?prop rdf:type rdf:Property.
    ?class rdf:type owl:Class.
    ?prop rdfs:domain ?class.
    ?class  owl:unionOf ( ?class1 ?class2 ) .
    # MINUS {
    #     ?prop rdfs:domain ?other.
    #     ?other rdfs:subClassOf ?class.
    #     MINUS {
    #         ?class rdfs:subClassOf ?other.
    #     } 
    # } 
    FILTER( !STRSTARTS(STR(?prop) , 'http://www.w3.org'))
 }